jobs:
  - name: preprod
    max_in_flight: 1
    plan:
      - get: dataworks-aws-ucfs-claimant-consumer
        trigger: true
        passed:
          - qa
      - .: (( inject meta.plan.terraform-bootstrap ))
      - .: (( inject meta.plan.terraform-apply ))
        params:
          TF_WORKSPACE: 'preprod'
      - .: (( inject meta.plan.terraform-plan ))
        params:
          TF_WORKSPACE: 'preprod'
